"""Central re-exports of all pre-computed introspection data.

This module aggregates version enums, weight mappings, and
compatibility maps for all supported operating systems, providing
a single entry point for the weight providers.
"""

from typing import Final

from tg_devices.enums.os import OS
from tg_devices.weight.introspection.android import (
    ANDROID_APP_VERSIONS,
    ANDROID_APP_WEIGHT_MAP,
    ANDROID_APP_WEIGHTS,
    ANDROID_COMPATIBILITY_MAP,
    ANDROID_DEVICE_MODELS,
    ANDROID_SYSTEM_VERSIONS,
    ANDROID_SYSTEM_WEIGHT_MAP,
    ANDROID_SYSTEM_WEIGHTS,
    ANDROID_WEIGHTS_DATA,
)
from tg_devices.weight.introspection.linux import (
    LINUX_APP_VERSIONS,
    LINUX_APP_WEIGHT_MAP,
    LINUX_APP_WEIGHTS,
    LINUX_COMPATIBILITY_MAP,
    LINUX_DEVICE_MODELS,
    LINUX_SYSTEM_VERSIONS,
    LINUX_SYSTEM_WEIGHT_MAP,
    LINUX_SYSTEM_WEIGHTS,
    LINUX_WEIGHTS_DATA,
)
from tg_devices.weight.introspection.macos import (
    MACOS_APP_VERSIONS,
    MACOS_APP_WEIGHT_MAP,
    MACOS_APP_WEIGHTS,
    MACOS_COMPATIBILITY_MAP,
    MACOS_DEVICE_MODELS,
    MACOS_SYSTEM_VERSIONS,
    MACOS_SYSTEM_WEIGHT_MAP,
    MACOS_SYSTEM_WEIGHTS,
    MACOS_WEIGHTS_DATA,
)
from tg_devices.weight.introspection.windows import (
    WINDOWS_APP_VERSIONS,
    WINDOWS_APP_WEIGHT_MAP,
    WINDOWS_APP_WEIGHTS,
    WINDOWS_COMPATIBILITY_MAP,
    WINDOWS_DEVICE_MODELS,
    WINDOWS_SYSTEM_VERSIONS,
    WINDOWS_SYSTEM_WEIGHT_MAP,
    WINDOWS_SYSTEM_WEIGHTS,
    WINDOWS_WEIGHTS_DATA,
)

OS_NAMES: Final[tuple[OS, ...]] = tuple(OS)

__all__ = [
    "OS_NAMES",
    "ANDROID_APP_VERSIONS",
    "ANDROID_APP_WEIGHT_MAP",
    "ANDROID_APP_WEIGHTS",
    "ANDROID_COMPATIBILITY_MAP",
    "ANDROID_DEVICE_MODELS",
    "ANDROID_SYSTEM_VERSIONS",
    "ANDROID_SYSTEM_WEIGHT_MAP",
    "ANDROID_SYSTEM_WEIGHTS",
    "ANDROID_WEIGHTS_DATA",
    "LINUX_APP_VERSIONS",
    "LINUX_APP_WEIGHT_MAP",
    "LINUX_APP_WEIGHTS",
    "LINUX_COMPATIBILITY_MAP",
    "LINUX_DEVICE_MODELS",
    "LINUX_SYSTEM_VERSIONS",
    "LINUX_SYSTEM_WEIGHT_MAP",
    "LINUX_SYSTEM_WEIGHTS",
    "LINUX_WEIGHTS_DATA",
    "MACOS_APP_VERSIONS",
    "MACOS_APP_WEIGHT_MAP",
    "MACOS_APP_WEIGHTS",
    "MACOS_COMPATIBILITY_MAP",
    "MACOS_DEVICE_MODELS",
    "MACOS_SYSTEM_VERSIONS",
    "MACOS_SYSTEM_WEIGHT_MAP",
    "MACOS_SYSTEM_WEIGHTS",
    "MACOS_WEIGHTS_DATA",
    "WINDOWS_APP_VERSIONS",
    "WINDOWS_APP_WEIGHT_MAP",
    "WINDOWS_APP_WEIGHTS",
    "WINDOWS_COMPATIBILITY_MAP",
    "WINDOWS_DEVICE_MODELS",
    "WINDOWS_SYSTEM_VERSIONS",
    "WINDOWS_SYSTEM_WEIGHT_MAP",
    "WINDOWS_SYSTEM_WEIGHTS",
    "WINDOWS_WEIGHTS_DATA",
]
